<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\User;
use App\Models\Job;

class BulkJobSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $testUserId = User::where('email', 'test@test.com')->value('id');

        if (!$testUserId) {
            $testUserId = User::first()?->id ?? User::factory()->create([
                'name' => 'Test Company',
                'email' => 'test@test.com',
                'password' => bcrypt('12345678'),
                'role' => 'company'
            ])->id;
        }

        $jobs = [
            [
                'title' => 'Frontend Developer',
                'description' => 'We are looking for a Senior Frontend Developer proficient in React, Tailwind CSS, and TypeScript. You will lead the development of our customer-facing web dashboard.',
                'salary' => 95000,
                'job_type' => 'Full-Time',
                'remote' => 1,
                'requirements' => 'Proficiency in React.js, modern CSS/Tailwind, TypeScript, 3+ years of experience.',
                'benefits' => 'Competitive salary, premium healthcare, flexible remote-first policy.',
                'tags' => 'react,frontend,typescript,tailwind',
                'address' => '100 Broadway, New York, NY',
                'city' => 'New York',
                'state' => 'New York',
                'zipcode' => '10005',
                'latitude' => '40.7078',
                'longitude' => '-74.0115',
                'company_name' => 'TechSprint Inc',
                'company_description' => 'TechSprint is a fast-growing digital agency building next-generation SaaS applications.',
                'company_website' => 'https://techsprint.example.com',
                'contact_phone' => '555-0101',
                'contact_email' => 'test@test.com',
            ],
            [
                'title' => 'Backend Architect',
                'description' => 'Seeking an experienced Backend Architect to design scalable APIs and manage PostgreSQL databases. Strong experience with Laravel and PHP 8.x is required.',
                'salary' => 130000,
                'job_type' => 'Full-Time',
                'remote' => 0,
                'requirements' => 'Strong experience with Laravel, PostgreSQL, PHP, Docker, system design.',
                'benefits' => '401(k) matching, dental & vision cover, annual learning stipend.',
                'tags' => 'laravel,php,backend,postgres',
                'address' => '500 Market St, San Francisco, CA',
                'city' => 'San Francisco',
                'state' => 'California',
                'zipcode' => '94105',
                'latitude' => '37.7897',
                'longitude' => '-122.4014',
                'company_name' => 'DataFlow Labs',
                'company_description' => 'DataFlow Labs specializes in real-time analytics solutions for global logistics companies.',
                'company_website' => 'https://dataflow.example.com',
                'contact_phone' => '555-0102',
                'contact_email' => 'test@test.com',
            ],
            [
                'title' => 'Full Stack Engineer',
                'description' => 'Join our core engineering team to work across the stack on new product features. Experience with Laravel/Livewire or React is highly desirable.',
                'salary' => 110000,
                'job_type' => 'Full-Time',
                'remote' => 1,
                'requirements' => 'Full stack development experience with Laravel and a modern JS framework (Vue/React).',
                'benefits' => 'Unlimited PTO, home office budget, wellness allowance.',
                'tags' => 'laravel,react,vue,fullstack',
                'address' => '200 E Randolph St, Chicago, IL',
                'city' => 'Chicago',
                'state' => 'Illinois',
                'zipcode' => '60601',
                'latitude' => '41.8853',
                'longitude' => '-87.6214',
                'company_name' => 'CloudScale',
                'company_description' => 'CloudScale provides serverless hosting optimization tools for developers globally.',
                'company_website' => 'https://cloudscale.example.com',
                'contact_phone' => '555-0103',
                'contact_email' => 'test@test.com',
            ],
            [
                'title' => 'DevOps Specialist',
                'description' => 'We are seeking a DevOps Specialist to help automate our CI/CD pipelines and manage our AWS cloud infrastructure.',
                'salary' => 115000,
                'job_type' => 'Full-Time',
                'remote' => 1,
                'requirements' => 'Deep knowledge of AWS, Terraform, GitHub Actions, Docker, and Kubernetes.',
                'benefits' => 'Flexible work hours, stock options, comprehensive health insurance.',
                'tags' => 'aws,devops,terraform,cicd',
                'address' => '1201 Third Ave, Seattle, WA',
                'city' => 'Seattle',
                'state' => 'Washington',
                'zipcode' => '98101',
                'latitude' => '47.6074',
                'longitude' => '-122.3361',
                'company_name' => 'OpsCore Systems',
                'company_description' => 'OpsCore Systems delivers robust monitoring and automation frameworks for cloud-native applications.',
                'company_website' => 'https://opscore.example.com',
                'contact_phone' => '555-0104',
                'contact_email' => 'test@test.com',
            ],
            [
                'title' => 'Data Scientist',
                'description' => 'Analyze large datasets and build predictive models to drive strategic product decisions. Strong statistics background required.',
                'salary' => 125000,
                'job_type' => 'Full-Time',
                'remote' => 1,
                'requirements' => 'Python/R, SQL, machine learning algorithms, solid background in probability/statistics.',
                'benefits' => 'Annual bonus, remote stipends, healthcare reimbursement.',
                'tags' => 'data,python,sql,ml',
                'address' => '600 Congress Ave, Austin, TX',
                'city' => 'Austin',
                'state' => 'Texas',
                'zipcode' => '78701',
                'latitude' => '30.2689',
                'longitude' => '-97.7422',
                'company_name' => 'DataMinds LLC',
                'company_description' => 'DataMinds provides custom business intelligence and ML models for retail operations.',
                'company_website' => 'https://dataminds.example.com',
                'contact_phone' => '555-0105',
                'contact_email' => 'test@test.com',
            ],
            [
                'title' => 'Machine Learning Engineer',
                'description' => 'Train, deploy, and scale deep learning models for natural language processing and computer vision challenges.',
                'salary' => 140000,
                'job_type' => 'Full-Time',
                'remote' => 0,
                'requirements' => 'PyTorch or TensorFlow, machine learning model deployment (MLOps), Python.',
                'benefits' => 'Competitive base salary, equity options, free gym membership.',
                'tags' => 'ml,pytorch,nlp,tensorflow',
                'address' => '100 Summer St, Boston, MA',
                'city' => 'Boston',
                'state' => 'Massachusetts',
                'zipcode' => '02110',
                'latitude' => '42.3536',
                'longitude' => '-71.0560',
                'company_name' => 'CognitiveAI',
                'company_description' => 'CognitiveAI is building next-gen conversational intelligence software for enterprises.',
                'company_website' => 'https://cognitiveai.example.com',
                'contact_phone' => '555-0106',
                'contact_email' => 'test@test.com',
            ],
            [
                'title' => 'Product Manager',
                'description' => 'Own the roadmap and feature execution for our developer platform. Coordinate with engineering, design, and marketing.',
                'salary' => 105000,
                'job_type' => 'Full-Time',
                'remote' => 1,
                'requirements' => '2+ years PM experience at a tech startup, technical background, excellent communication.',
                'benefits' => 'Bonus pool, unlimited vacation, mental health days.',
                'tags' => 'product,management,agile,roadmap',
                'address' => '3000 Sand Hill Rd, Menlo Park, CA',
                'city' => 'Menlo Park',
                'state' => 'California',
                'zipcode' => '94025',
                'latitude' => '37.4267',
                'longitude' => '-122.2036',
                'company_name' => 'StartUp Labs',
                'company_description' => 'StartUp Labs builds early-stage collaboration platforms for developers and teams.',
                'company_website' => 'https://startuplabs.example.com',
                'contact_phone' => '555-0107',
                'contact_email' => 'test@test.com',
            ],
            [
                'title' => 'UX Designer',
                'description' => 'Design clean, beautiful, and highly functional user experiences. Create interactive wireframes and conduct user interviews.',
                'salary' => 90000,
                'job_type' => 'Full-Time',
                'remote' => 1,
                'requirements' => 'Figma mastery, strong UX portfolio, experience conducting user research.',
                'benefits' => 'Flexible working hours, yearly creative software stipend, healthcare options.',
                'tags' => 'ux,figma,design,ui',
                'address' => '111 SW 5th Ave, Portland, OR',
                'city' => 'Portland',
                'state' => 'Oregon',
                'zipcode' => '97204',
                'latitude' => '45.5204',
                'longitude' => '-122.6784',
                'company_name' => 'PixelPerfect',
                'company_description' => 'PixelPerfect is an award-winning design studio specializing in UI/UX and branding.',
                'company_website' => 'https://pixelperfect.example.com',
                'contact_phone' => '555-0108',
                'contact_email' => 'test@test.com',
            ],
            [
                'title' => 'QA Analyst',
                'description' => 'Write automated testing scripts and carry out manual checks to guarantee high-quality releases.',
                'salary' => 78000,
                'job_type' => 'Full-Time',
                'remote' => 0,
                'requirements' => 'Playwright/Cypress experience, manual testing experience, bug tracking tools.',
                'benefits' => 'Paid time off, health insurance, free lunch daily.',
                'tags' => 'qa,testing,cypress,automation',
                'address' => '400 N Ervay St, Dallas, TX',
                'city' => 'Dallas',
                'state' => 'Texas',
                'zipcode' => '75201',
                'latitude' => '32.7845',
                'longitude' => '-96.7972',
                'company_name' => 'SecureCode Solutions',
                'company_description' => 'SecureCode Solutions helps financial companies audit and secure their code bases.',
                'company_website' => 'https://securecode.example.com',
                'contact_phone' => '555-0109',
                'contact_email' => 'test@test.com',
            ],
            [
                'title' => 'Cloud Engineer',
                'description' => 'Maintain multi-cloud architectures, automate environment provisioning, and optimize cloud infrastructure costs.',
                'salary' => 112000,
                'job_type' => 'Full-Time',
                'remote' => 1,
                'requirements' => 'AWS/GCP certification, Kubernetes, Docker, bash scripting, network topologies.',
                'benefits' => 'Generous dental, vision and health insurance, learning budget.',
                'tags' => 'cloud,gcp,aws,kubernetes',
                'address' => '700 Louisiana St, Houston, TX',
                'city' => 'Houston',
                'state' => 'Texas',
                'zipcode' => '77002',
                'latitude' => '29.7589',
                'longitude' => '-95.3678',
                'company_name' => 'Apex Cloud Systems',
                'company_description' => 'Apex Cloud Systems builds specialized infrastructure scaling solutions for e-commerce clients.',
                'company_website' => 'https://apexcloud.example.com',
                'contact_phone' => '555-0110',
                'contact_email' => 'test@test.com',
            ],
            [
                'title' => 'iOS Developer',
                'description' => 'Develop native mobile applications using Swift and SwiftUI. Focus on UI details and performance.',
                'salary' => 102000,
                'job_type' => 'Full-Time',
                'remote' => 1,
                'requirements' => 'Swift, SwiftUI, iOS SDK, experience submitting apps to App Store.',
                'benefits' => 'Annual hardware upgrade, health cover, learning stipend.',
                'tags' => 'ios,swift,swiftui,mobile',
                'address' => '200 Clarendon St, Boston, MA',
                'city' => 'Boston',
                'state' => 'Massachusetts',
                'zipcode' => '02116',
                'latitude' => '42.3499',
                'longitude' => '-71.0772',
                'company_name' => 'SwiftLabs Co',
                'company_description' => 'SwiftLabs designs user-centric mobile applications for lifestyle and productivity brands.',
                'company_website' => 'https://swiftlabs.example.com',
                'contact_phone' => '555-0111',
                'contact_email' => 'test@test.com',
            ],
            [
                'title' => 'Android Specialist',
                'description' => 'Create state-of-the-art native Android applications utilizing Kotlin, Jetpack Compose, and modern architecture libraries.',
                'salary' => 101000,
                'job_type' => 'Full-Time',
                'remote' => 1,
                'requirements' => 'Kotlin, Jetpack Compose, Coroutines, MVVM architecture, 3+ years experience.',
                'benefits' => 'Stock packages, work-from-anywhere allowance, flexible hours.',
                'tags' => 'android,kotlin,compose,mobile',
                'address' => '601 Delaware Ave, Wilmington, DE',
                'city' => 'Wilmington',
                'state' => 'Delaware',
                'zipcode' => '19801',
                'latitude' => '39.7431',
                'longitude' => '-75.5512',
                'company_name' => 'DroidCore Systems',
                'company_description' => 'DroidCore builds performance-driven SDKs and custom business apps for Android platforms.',
                'company_website' => 'https://droidcore.example.com',
                'contact_phone' => '555-0112',
                'contact_email' => 'test@test.com',
            ],
            [
                'title' => 'Security Engineer',
                'description' => 'Identify potential security vulnerabilities, conduct penetration tests, and secure internal system communications.',
                'salary' => 128000,
                'job_type' => 'Full-Time',
                'remote' => 0,
                'requirements' => 'Certifications like CISSP/OSCP, scripting skills, secure network protocols, threat modeling.',
                'benefits' => 'Health & wellness stipends, quarterly bonuses, fully paid conference visits.',
                'tags' => 'security,penetration,cryptography,cyber',
                'address' => '1001 Woodward Ave, Detroit, MI',
                'city' => 'Detroit',
                'state' => 'Michigan',
                'zipcode' => '48226',
                'latitude' => '42.3314',
                'longitude' => '-83.0458',
                'company_name' => 'Sentinel Defense',
                'company_description' => 'Sentinel Defense provides active security monitoring and cyber threat solutions for commercial entities.',
                'company_website' => 'https://sentinel.example.com',
                'contact_phone' => '555-0113',
                'contact_email' => 'test@test.com',
            ],
            [
                'title' => 'Database Administrator',
                'description' => 'Ensure database security, optimize SQL queries, structure storage engines, and manage data recovery strategies.',
                'salary' => 96000,
                'job_type' => 'Part-Time',
                'remote' => 1,
                'requirements' => 'Advanced query tuning, replication, backup strategies, MySQL/PostgreSQL expertise.',
                'benefits' => 'Flexible hourly contract, professional development sponsorship.',
                'tags' => 'database,sql,mysql,postgres',
                'address' => '1600 Amphitheatre Pkwy, Mountain View, CA',
                'city' => 'Mountain View',
                'state' => 'California',
                'zipcode' => '94043',
                'latitude' => '37.4220',
                'longitude' => '-122.0841',
                'company_name' => 'QueryOptima',
                'company_description' => 'QueryOptima provides cloud-based index and query performance enhancement solutions.',
                'company_website' => 'https://queryoptima.example.com',
                'contact_phone' => '555-0114',
                'contact_email' => 'test@test.com',
            ],
            [
                'title' => 'Scrum Master',
                'description' => 'Facilitate agile sprint rituals, resolve project blockers, and align development timelines with cross-functional milestones.',
                'salary' => 92000,
                'job_type' => 'Full-Time',
                'remote' => 0,
                'requirements' => 'Certified Scrum Master (CSM), excellent facilitation, conflict resolution skills.',
                'benefits' => 'Commuter benefits, free lunch, health insurance.',
                'tags' => 'scrum,agile,sprint,management',
                'address' => '1900 L St NW, Washington, DC',
                'city' => 'Washington',
                'state' => 'District of Columbia',
                'zipcode' => '20036',
                'latitude' => '38.9038',
                'longitude' => '-77.0435',
                'company_name' => 'AgileVantage Group',
                'company_description' => 'AgileVantage assists growing startups in structuring high-performing team operational loops.',
                'company_website' => 'https://agilevantage.example.com',
                'contact_phone' => '555-0115',
                'contact_email' => 'test@test.com',
            ],
            [
                'title' => 'Technical Writer',
                'description' => 'Draft developer-focused API references, tutorials, integration instructions, and technical documentation.',
                'salary' => 82000,
                'job_type' => 'Part-Time',
                'remote' => 1,
                'requirements' => 'Knowledge of Markdown/Git, ability to read code (PHP/JS), portfolio of documentation.',
                'benefits' => 'Work-from-home stipend, flexible project delivery cycles.',
                'tags' => 'docs,technical,writing,api',
                'address' => '2201 Westlake Ave, Seattle, WA',
                'city' => 'Seattle',
                'state' => 'Washington',
                'zipcode' => '98121',
                'latitude' => '47.6186',
                'longitude' => '-122.3384',
                'company_name' => 'DocuTech Inc',
                'company_description' => 'DocuTech helps technology businesses write, host, and publish structured developer portals.',
                'company_website' => 'https://docutech.example.com',
                'contact_phone' => '555-0116',
                'contact_email' => 'test@test.com',
            ],
            [
                'title' => 'Solutions Architect',
                'description' => 'Collaborate with enterprise clients to plan system integrations, hybrid architectures, and API patterns.',
                'salary' => 135000,
                'job_type' => 'Full-Time',
                'remote' => 1,
                'requirements' => 'Enterprise integration patterns, cloud platform certifications, background in systems engineering.',
                'benefits' => 'Health & dental cover, stock plan, executive wellness checkups.',
                'tags' => 'architecture,enterprise,solutions,api',
                'address' => '600 Peachtree St NE, Atlanta, GA',
                'city' => 'Atlanta',
                'state' => 'Georgia',
                'zipcode' => '30308',
                'latitude' => '33.7712',
                'longitude' => '-84.3858',
                'company_name' => 'IntegraScale LLC',
                'company_description' => 'IntegraScale delivers robust integration consulting and middleware for corporate enterprise scales.',
                'company_website' => 'https://integrascale.example.com',
                'contact_phone' => '555-0117',
                'contact_email' => 'test@test.com',
            ],
            [
                'title' => 'Reliability Engineer',
                'description' => 'Focus on system uptime, disaster recovery simulation, error budgeting, and real-time response automation.',
                'salary' => 122000,
                'job_type' => 'Full-Time',
                'remote' => 1,
                'requirements' => 'Linux administration, container orchestration (Kubernetes), load balancing architectures.',
                'benefits' => 'On-call compensation pool, flexible remote policy, learning allowances.',
                'tags' => 'sre,reliability,uptime,linux',
                'address' => '1515 Arapahoe St, Denver, CO',
                'city' => 'Denver',
                'state' => 'Colorado',
                'zipcode' => '80202',
                'latitude' => '39.7497',
                'longitude' => '-104.9961',
                'company_name' => 'UptimeLabs Co',
                'company_description' => 'UptimeLabs provides automated high-availability disaster recovery simulations for enterprise SaaS.',
                'company_website' => 'https://uptimelabs.example.com',
                'contact_phone' => '555-0118',
                'contact_email' => 'test@test.com',
            ],
            [
                'title' => 'Product Analyst',
                'description' => 'Run SQL queries, extract usage patterns, and synthesize analytics reports to guide feature refinements.',
                'salary' => 86000,
                'job_type' => 'Full-Time',
                'remote' => 1,
                'requirements' => 'Advanced SQL, analytics tools (Mixpanel/Amplitude/Tableau), clean data visualization skills.',
                'benefits' => 'Health insurance, annual gym stipend, remote setup budget.',
                'tags' => 'analytics,sql,product,tableau',
                'address' => '101 Marietta St NW, Atlanta, GA',
                'city' => 'Atlanta',
                'state' => 'Georgia',
                'zipcode' => '30303',
                'latitude' => '33.7570',
                'longitude' => '-84.3912',
                'company_name' => 'MetricGroup LLC',
                'company_description' => 'MetricGroup provides detailed product-market fit analysis tools and consulting for startups.',
                'company_website' => 'https://metricgroup.example.com',
                'contact_phone' => '555-0119',
                'contact_email' => 'test@test.com',
            ],
            [
                'title' => 'IT Administrator',
                'description' => 'Manage employee hardware setups, configure cloud service authorizations, and oversee security policies.',
                'salary' => 80000,
                'job_type' => 'Full-Time',
                'remote' => 0,
                'requirements' => 'SaaS directory management (Okta/ActiveDirectory), MDM provisioning, networking essentials.',
                'benefits' => 'Full medical dental coverage, standard annual bonus pool.',
                'tags' => 'it,system,okta,network',
                'address' => '233 S Wacker Dr, Chicago, IL',
                'city' => 'Chicago',
                'state' => 'Illinois',
                'zipcode' => '60606',
                'latitude' => '41.8789',
                'longitude' => '-87.6358',
                'company_name' => 'SaaS Admin Partners',
                'company_description' => 'SaaS Admin Partners handles fractional IT support and directory integrations for digital companies.',
                'company_website' => 'https://saasadmins.example.com',
                'contact_phone' => '555-0120',
                'contact_email' => 'test@test.com',
            ]
        ];

        foreach ($jobs as $jobData) {
            $jobData['user_id'] = $testUserId;
            $jobData['created_at'] = now();
            $jobData['updated_at'] = now();
            Job::create($jobData);
        }

        $this->command->info('Seeded 20 jobs successfully for test@test.com!');
    }
}
